[project]
name = "joutub-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord>=2.3.2",
    "discord-py>=2.5.2",
    "numpy>=2.3.1",
    "pandas>=2.3.0",
    "requests>=2.32.4",
]
